### PR TITLE
Grust((((((((((((

### PR DESCRIPTION
**Pull request by ayeKent**

### CODE REVIEW

**Comment by oleksandrmytro** [comment]
ne grusti

**Comment by ayeKent** [comment]
😮
🤙
Baba Luba

Чт, 5 дек. 2024 г. в 19:56, Oleksandr Mytro ***@***.***>:

**Comment by oleksandrmytro** [comment]
😮
🤙
Tumba Umba

### Search Filters and Categories:

* [`public/pages/search.html`](diffhunk://#diff-47921ce0865d63630f9fb403c9c057e0beed0a7d35b29d7ba893a122942353f9L60-R70): Updated the search filter buttons to include new categories like "Sweet", "Grilled", and "Soups", and capitalized existing categories.

### Search Script Enhancements:

* [`public/scripts/search.js`](diffhunk://#diff-05fdc2b7120c8733c698155ed9f50fdf6718f18589a259d5f95b19c0df859be6L337-R469): Refactored the search script to improve the filtering and search functionality. This includes adding event listeners for filter buttons and the search bar, fetching recipes based on category or search query, and displaying recipes with updated card details. [[1]](diffhunk://#diff-05fdc2b7120c8733c698155ed9f50fdf6718f18589a259d5f95b19c0df859be6L337-R469) [[2]](diffhunk://#diff-05fdc2b7120c8733c698155ed9f50fdf6718f18589a259d5f95b19c0df859be6L458-R492)

### CSS Styling Improvements:

* [`public/styles/search.css`](diffhunk://#diff-fbd55b2335431b1dd1ef7ca58da9b419a74df9ae685c2a7e54ae6e810c1f0910L159-R166): Adjusted the styling for recipe images, added new styles for QR codes and recipe links to enhance the visual presentation of the recipes. [[1]](diffhunk://#diff-fbd55b2335431b1dd1ef7ca58da9b419a74df9ae685c2a7e54ae6e810c1f0910L159-R166) [[2]](diffhunk://#diff-fbd55b2335431b1dd1ef7ca58da9b419a74df9ae685c2a7e54ae6e810c1f0910R246-R261)

### Minor Changes:

* [`public/scripts/search.js`](diffhunk://#diff-05fdc2b7120c8733c698155ed9f50fdf6718f18589a259d5f95b19c0df859be6L13-R13): Corrected a comment format for consistency.
* [`php.ini`](diffhunk://#diff-243dae866e7173c76f8b91864096c15ffcb3aec3699da130eb0b7ef2566fdce3R4): Added the `mysql` extension.mba

**Comment by ayeKent** [comment]
🦾🏋️🕐❓


Чт, 5 дек. 2024 г. в 20:01, Oleksandr Mytro ***@***.***>:

**Comment by oleksandrmytro** [comment]
**⏰ В 10:00?!** 😱🤯🫨  
*Серйозно?!* 😵‍💫🔥💔  
🛌😴💤 ➡️ 😳🤦‍♂️😭 ➡️ 😩😵  
*Як так рано?!* 🕙❌😔  
☕🙏☕☕ *Тільки кава врятує…* 💀⚰️  
🫥🫣➡️ *Може, це сон?* 🪄✨

**Pull request merged**
